# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = me.p0x38
archives_name = fuckinguselessmod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
architectury_api_version = 19.0.1
fabric_loader_version = 0.19.5
fabric_api_version = 0.141.6+1.21.11
neoforge_version = 21.11.45

# Client / configuration dependencies
cloth_config_version = 21.11.153
modmenu_version = 17.0.1
text_placeholder_api_version = 2.8.2+1.21.10
devauth_version = 1.2.2
sodium_version = 0.8.14
