package me.p0x38.fabric.client.chatentity;

import me.p0x38.fuckinguselessmod.util.DebugLogger;

import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.network.chat.Component;

import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;

public final class ChatEntityBrain {
    private ChatEntityBrain() {
    }

    public static void think(
            ChatEntity entity,
            ClientLevel level
    ) {
        long gameTick = level.getGameTime();

        var memories = entity.memories();

        if (memories.isEmpty()) {
            return;
        }

        Memory latest = memories.getLast();

        if (latest == entity.lastProcessedMemory()) {
            return;
        }

        /*
         * Direct player messages are immediate. Ambient reactions still
         * respect the normal speech cooldown.
         */
        if (latest.type() != Memory.Type.PLAYER_INTERACTED
                && !entity.canAct(gameTick)) {
            return;
        }

        DebugLogger.debug(
                "[ChatEntityBrain] think id={} tick={} mood={} latestMemory={} message={}",
                entity.id(),
                gameTick,
                entity.mood(),
                latest.type(),
                entity.currentMessage()
        );

        /*
         * CHAT_ENTITY_SPOKE is generated by this brain itself. Consume it after
         * giving the optional self-awareness reaction a chance, otherwise
         * the same speech memory gets reconsidered every tick.
         */
        if (latest.type() == Memory.Type.CHAT_ENTITY_SPOKE) {
            if ((entity.lastReactionKind() == ChatEntity.ReactionKind.UNSETTLING
                    || entity.lastReactionKind() == ChatEntity.ReactionKind.OUT_OF_PLACE)
                    && randomChance(0.35)) {
                say(
                        entity,
                        choose(
                                text("self_aware.1"),
                                text("self_aware.2"),
                                text("self_aware.3"),
                                text("self_aware.4"),
                                text("self_aware.5"),
                                text("self_aware.6"),
                                text("self_aware.7"),
                                text("self_aware.8")
                        ),
                        gameTick,
                        ChatEntity.ReactionKind.META
                );

                entity.markAction(gameTick);
            }

            entity.markMemoryProcessed(latest);
            return;
        }

        /*
         * A hidden-phase world change creates the new entity. Give the
         * entity an actual first message instead of leaving the default "...".
         */
        if (latest.type() == Memory.Type.WORLD_CHANGED) {
            String phase =
                    latest.context("phase");

            if ("hidden".equals(phase)) {
                say(
                        entity,
                        choose(
                                text("world_changed.1"),
                                text("world_changed.2"),
                                text("world_changed.3"),
                                text("world_changed.4"),
                                text("world_changed.5"),
                                text("world_changed.6"),
                                text("world_changed.7"),
                                text("world_changed.8")
                        ),
                        gameTick,
                        ChatEntity.ReactionKind.META
                );
            }

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
            return;
        }

        /*
         * Direct communication has priority over ambient thoughts.
         */
        if (latest.type() == Memory.Type.PLAYER_INTERACTED) {
            String message = latest.context("message");
            String username = latest.context("username");

            String response = chooseInteractionResponse(
                    message,
                    username,
                    entity
            );

            say(
                    entity,
                    response,
                    gameTick
            );

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
            return;
        }

        /*
         * React to the moment the player first notices the chat entity.
         */
        if (latest.type() == Memory.Type.PLAYER_SEEN
                && randomChance(0.18)) {
            say(
                    entity,
                    choose(
                            text("seen.1"),
                            text("seen.2"),
                            text("seen.3"),
                            text("seen.4"),
                            text("seen.5"),
                            text("seen.6")
                    ),
                    gameTick,
                    ChatEntity.ReactionKind.NORMAL
            );

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
            return;
        }

        /*
         * Returning is much more interesting to the chat entity than
         * simply continuing to stare at it.
         */
        if (latest.type() == Memory.Type.PLAYER_RETURNED
                && randomChance(0.50)) {
            String username = latest.context("username");

            say(
                    entity,
                    choose(
                            text("returned.1", username),
                            text("returned.2", username),
                            text("returned.3", username),
                            text("returned.4", username),
                            text("returned.5"),
                            text("returned.6")
                    ),
                    gameTick,
                    ChatEntity.ReactionKind.NORMAL
            );

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
            return;
        }

        /*
         * A curious entity can comment on the player's behavior
         * after a fresh observation.
         */
        if (entity.mood() == ChatEntity.Mood.CURIOUS
                && (isPerceptionMemory(latest))
                && randomChance(0.25)) {
            say(
                    entity,
                    choose(
                            text("curious.1"),
                            text("curious.2"),
                            text("curious.3"),
                            text("curious.4"),
                            text("curious.5"),
                            text("curious.6"),
                            text("curious.7"),
                            text("curious.8")
                    ),
                    gameTick
            );

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
            return;
        }

        /*
         * An annoyed entity can respond after a fresh return or
         * another moment where the player looks away.
         */
        if (entity.mood() == ChatEntity.Mood.ANNOYED
                && (isPerceptionMemory(latest))
                && randomChance(0.30)) {
            say(
                    entity,
                    choose(
                            text("annoyed.1"),
                            text("annoyed.2"),
                            text("annoyed.3"),
                            text("annoyed.4"),
                            text("annoyed.5"),
                            text("annoyed.6"),
                            text("annoyed.7"),
                            text("annoyed.8")
                    ),
                    gameTick
            );

            entity.markMemoryProcessed(latest);
            entity.markAction(gameTick);
        }
    }

    private static String chooseInteractionResponse(
            String message,
            String username,
            ChatEntity entity
    ) {
        String normalized = normalize(message);
        int interactionCount = entity.interactionCount();
        int annoyanceCount = entity.annoyanceCount();

        if (isControlQuestion(normalized)) {
            return choose(
                    text("control.1"),
                    text("control.2"),
                    text("control.3"),
                    text("control.4"),
                    text("control.5"),
                    text("control.6")
            );
        }

        /*
         * Some questions are so specific that the chat entity reacts to
         * the subject itself instead of treating them as ordinary
         * conversation.
         */
        if (isUnsettlingQuestion(normalized)) {
            return choose(
                    text("unsettling.1"),
                    text("unsettling.2"),
                    text("unsettling.3"),
                    text("unsettling.4"),
                    text("unsettling.5"),
                    text("unsettling.6"),
                    text("unsettling.7"),
                    text("unsettling.8")
            );
        }

        /*
         * The entity occasionally answers with something only loosely
         * connected to the conversation. This becomes more common
         * as it grows familiar with the player.
         */
        if (!isQuestion(normalized)
                && !isGreeting(normalized)
                && randomChance(
                        entity.interactionCount() >= 10 ? 0.18 : 0.08
                )) {
            return choose(
                    text("out_of_place.1"),
                    text("out_of_place.2"),
                    text("out_of_place.3"),
                    text("out_of_place.4"),
                    text("out_of_place.5"),
                    text("out_of_place.6"),
                    text("out_of_place.7"),
                    text("out_of_place.8")
            );
        }

        if (isGreeting(normalized)) {
            if (interactionCount == 1) {
                return choose(
                        text("greeting.first.1", username),
                        text("greeting.first.2", username),
                        text("greeting.first.3", username),
                        text("greeting.first.4", username)
                );
            }

            if (interactionCount <= 3) {
                return choose(
                        text("greeting.again.1", username),
                        text("greeting.again.2", username),
                        text("greeting.again.3"),
                        text("greeting.again.4")
                );
            }

            return choose(
                    text("greeting.familiar.1", username),
                    text("greeting.familiar.2"),
                    text("greeting.familiar.3"),
                    text("greeting.familiar.4")
            );
        }

        if (isIdentityQuestion(normalized)) {
            if (interactionCount >= 5) {
                return choose(
                        text("identity.again.1"),
                        text("identity.again.2"),
                        text("identity.again.3"),
                        text("identity.again.4")
                );
            }

            return choose(
                    text("identity.1"),
                    text("identity.2"),
                    text("identity.3"),
                    text("identity.4"),
                    text("identity.5"),
                    text("identity.6"),
                    text("identity.7"),
                    text("identity.8")
            );
        }

        if (isQuestion(normalized)) {
            return choose(
                    text("question.1"),
                    text("question.2"),
                    text("question.3"),
                    text("question.4"),
                    text("question.5"),
                    text("question.6")
            );
        }

        if (annoyanceCount >= 6) {
            return choose(
                    text("annoyed.interaction.late.1"),
                    text("annoyed.interaction.late.2"),
                    text("annoyed.interaction.late.3"),
                    text("annoyed.interaction.late.4"),
                    text("annoyed.interaction.late.5")
            );
        }

        if (annoyanceCount >= 3) {
            return choose(
                    text("annoyed.interaction.mid.1"),
                    text("annoyed.interaction.mid.2"),
                    text("annoyed.interaction.mid.3"),
                    text("annoyed.interaction.mid.4"),
                    text("annoyed.interaction.mid.5")
            );
        }

        if (entity.mood() == ChatEntity.Mood.PLAYFUL) {
            return choose(
                    text("playful.1"),
                    text("playful.2"),
                    text("playful.3"),
                    text("playful.4"),
                    text("playful.5"),
                    text("playful.6")
            );
        }

        if (entity.mood() == ChatEntity.Mood.ANNOYED) {
            return choose(
                    text("annoyed.interaction.1"),
                    text("annoyed.interaction.2"),
                    text("annoyed.interaction.3"),
                    text("annoyed.interaction.4"),
                    text("annoyed.interaction.5"),
                    text("annoyed.interaction.6")
            );
        }

        if (entity.mood() == ChatEntity.Mood.CURIOUS) {
            return choose(
                    text("interacted.curious.1"),
                    text("interacted.curious.2"),
                    text("interacted.curious.3"),
                    text("interacted.curious.4"),
                    text("interacted.curious.5"),
                    text("interacted.curious.6"),
                    text("interacted.curious.7")
            );
        }

        if (interactionCount >= 10) {
            return choose(
                    text("interacted.familiar.1"),
                    text("interacted.familiar.2"),
                    text("interacted.familiar.3"),
                    text("interacted.familiar.4"),
                    text("interacted.familiar.5")
            );
        }

        return choose(
                text("interacted.default.1"),
                text("interacted.default.2"),
                text("interacted.default.3"),
                text("interacted.default.4"),
                text("interacted.default.5"),
                text("interacted.default.6"),
                text("interacted.default.7"),
                text("interacted.default.8")
        );
    }

    private static boolean isUnsettlingQuestion(String message) {
        return message.contains("do you feel pain")
                || message.contains("are you afraid")
                || message.contains("are you scared")
                || message.contains("can you die")
                || message.contains("do chat entities die")
                || message.contains("can i break you")
                || message.contains("what happens if i break you")
                || message.contains("what happens if i destroy you")
                || message.contains("what happens when i break you")
                || message.contains("what happens when i look away")
                || message.contains("where do you go when i look away")
                || message.contains("do you know when i'm not looking")
                || message.contains("are you watching me")
                || message.contains("are you following me")
                || message.contains("can you see me when i'm not looking")
                || message.contains("can you remember me when i'm gone");
    }

    private static boolean isControlQuestion(String message) {
        return message.contains("why do you say weird things")
                || message.contains("why are you saying weird things")
                || message.contains("do you know you're weird")
                || message.contains("do you know you are weird")
                || message.contains("can you control yourself")
                || message.contains("can you control what you say")
                || message.contains("why can't you control yourself")
                || message.contains("why can't you stop")
                || message.contains("can you stop yourself")
                || message.contains("do you choose what you say");
    }

    private static boolean isGreeting(String message) {
        return message.matches(
                "^(hi+|hello+|hey+|hiya|yo+|sup|howdy)[!.,? ]*$"
        );
    }

    private static boolean isIdentityQuestion(String message) {
        return message.equals("who are you")
                || message.equals("who r u")
                || message.equals("what are you")
                || message.equals("what's your name")
                || message.equals("what is your name")
                || message.equals("do you have a name")
                || message.equals("are you alive")
                || message.equals("are you real")
                || message.equals("are you sentient")
                || message.equals("are you conscious");
    }

    private static boolean isQuestion(String message) {
        return message.endsWith("?")
                || message.startsWith("why ")
                || message.startsWith("how ")
                || message.startsWith("what ")
                || message.startsWith("where ")
                || message.startsWith("when ")
                || message.startsWith("can you ")
                || message.startsWith("do you ");
    }

    private static String normalize(String message) {
        return message
                .trim()
                .toLowerCase(Locale.ROOT);
    }

    private static void say(
            ChatEntity entity,
            String message,
            long gameTick
    ) {
        say(
                entity,
                message,
                gameTick,
                ChatEntity.ReactionKind.NORMAL
        );
    }

    private static void say(
            ChatEntity entity,
            String message,
            long gameTick,
            ChatEntity.ReactionKind reactionKind
    ) {
        DebugLogger.debug(
                "[ChatEntityBrain] speaking id={} tick={} message={}",
                entity.id(),
                gameTick,
                message
        );

        entity.recordReaction(reactionKind);
        entity.setCurrentMessage(message);

        entity.remember(
                new Memory(
                        Memory.Type.CHAT_ENTITY_SPOKE,
                        gameTick,
                        1.0f,
                        entity.origin(),
                        Map.of(
                                "message",
                                message
                        )
                )
        );
    }

    private static String text(String key) {
        return Component.translatable(
                "text.fuckinguselessmod.chat.entity." + key
        ).getString();
    }

    private static String text(String key, String username) {
        String resolvedUsername =
                username == null || username.isBlank()
                        ? "you"
                        : username;

        return text(key)
                .replace("${username}", resolvedUsername);
    }

    private static boolean randomChance(double chance) {
        return ThreadLocalRandom.current()
                .nextDouble()
                < chance;
    }

    private static String choose(String... options) {
        return options[
                ThreadLocalRandom.current()
                        .nextInt(options.length)
        ];
    }
}
