modLoader = "javafml"
loaderVersion = "[4,)"
license = "All-Rights-Reserved"

[[mods]]
modId = "fuckinguselessmod"
version = "${version}"
displayName = "Fucking Useless Mod"
authors = "p0x38"
description = '''
Literally it adds some fucking useless stuffs!
'''

[[dependencies.fuckinguselessmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fuckinguselessmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fuckinguselessmod]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.fuckinguselessmod]]
modId = "cloth-config"
type = "required"
versionRange = "[21.11,)"
ordering = "AFTER"
side = "CLIENT"
